version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  geolocation-service:
    container_name: geolocation-service
    build:
      context: app/consumer
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 5001
    ports:
      - 5001:5001
    volumes:
      - ./app/consumer:/geolocation_service
    environment:
      - KAFKA_TOPICS=geolocation_service
      - KAFKA_HOST=broker
      - KAFKA_PORT=9092
      - DB=defaultdb
      - DB_USERNAME=doadmin
      - DB_PASSWORD=AVNS_hwAhxIrLgLdojpe88iP
      - DB_HOST=geolocation-service-db-do-user-9540197-0.b.db.ondigitalocean.com
      - DB_PORT=25060
    depends_on:
      - broker
      - zookeeper
